// This file is automatically generated. Do not modify it manually.

// Follow the instructions in the Firebase console to configure your app.
// https://firebase.google.com/docs/web/setup
export const firebaseConfig = {
  "projectId": "nextn"
};
